/*
 * The MIT License
 *
 * Copyright (c) 2014 Red Hat, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.github.olivergondza.dumpling.factory;

import static com.github.olivergondza.dumpling.Util.pause;
import static com.github.olivergondza.dumpling.model.ProcessThread.nameIs;
import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.nullValue;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;
import java.net.URISyntaxException;

import javax.annotation.Nonnull;

import org.hamcrest.Matchers;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.MethodRule;
import org.junit.runners.model.FrameworkMethod;
import org.junit.runners.model.Statement;

import com.github.olivergondza.dumpling.Util;
import com.github.olivergondza.dumpling.model.ProcessRuntime;
import com.github.olivergondza.dumpling.model.ProcessThread;
import com.github.olivergondza.dumpling.model.StackTrace;
import com.github.olivergondza.dumpling.model.ThreadLock;
import com.github.olivergondza.dumpling.model.ThreadStatus;

/**
 * Make sure threaddump generated by vendor of current JVM can be read by dumpling.
 *
 * Rule will start groovy script from <tt>src/test/resources/com/github/olivergondza/dumpling/factory/ThreadDumpFactoryVendorTest/METHOD_NAME.groovy</tt>
 * in separated process. SUT is picked up by <tt>sut.runtime()</tt> or
 * <tt>sut.thread("name")</tt>, the method will wait for process to be ready.
 *
 * @author ogondza
 */
public class ThreadDumpFactoryVendorTest {

    public @Rule Runner sut = new Runner();

    @Test
    public void busyWaiting() {
        ProcessThread main = sut.thread("main");
        assertThat(main.getStatus(), equalTo(ThreadStatus.RUNNABLE));
        assertThat(main.getAcquiredLocks(), Matchers.<ThreadLock>empty());
        assertThat(main.getWaitingToLock(), nullValue());
    }

    @Test
    public void waiting() {
        ProcessThread main = sut.thread("main");
        assertThat(main.getStatus(), equalTo(ThreadStatus.IN_OBJECT_WAIT));
        assertThat(main.getAcquiredLocks(), Matchers.<ThreadLock>empty());
        assertThat(main.getWaitingToLock(), nullValue());
    }

    @Test
    public void sleeping() {
        ProcessThread main = sut.thread("main");
        assertThat(main.getStatus(), equalTo(ThreadStatus.SLEEPING));
        assertThat(main.getAcquiredLocks(), Matchers.<ThreadLock>empty());
        assertThat(main.getWaitingToLock(), nullValue());
        assertThat(
                main.getStackTrace().getElement(0),
                equalTo(StackTrace.nativeElement("java.lang.Thread", "sleep"))
        );
    }

    @Test
    public void monitorDeadlock() {
        ProcessThread main = sut.thread("main");
        ProcessThread other = sut.thread("other");
        assertThat(main.getStatus(), equalTo(ThreadStatus.BLOCKED));
        assertThat(other.getStatus(), equalTo(ThreadStatus.BLOCKED));

        assertThat(main.getWaitingToLock(), equalTo(other.getAcquiredMonitors().iterator().next()));
        assertThat(other.getWaitingToLock(), equalTo(main.getAcquiredMonitors().iterator().next()));

        assertThat(other.getAcquiredSynchronizers(), Matchers.<ThreadLock>empty());
        assertThat(main.getAcquiredSynchronizers(), Matchers.<ThreadLock>empty());
    }

    @Test
    public void synchronizerDeadlock() {
        ProcessThread main = sut.thread("main");
        ProcessThread other = sut.thread("other");
        assertThat(main.getStatus(), equalTo(ThreadStatus.PARKED));
        assertThat(other.getStatus(), equalTo(ThreadStatus.PARKED));

        assertThat(main.getWaitingToLock(), equalTo(other.getAcquiredSynchronizers().iterator().next()));
        assertThat(other.getWaitingToLock(), equalTo(main.getAcquiredSynchronizers().iterator().next()));

        assertThat(other.getAcquiredMonitors(), Matchers.<ThreadLock>empty());
        assertThat(main.getAcquiredMonitors(), Matchers.<ThreadLock>empty());
    }

    @Test
    public void reacquireMonitorAfterWait() {
        ProcessThread reacquiring = sut.thread("reacquiring");
        ProcessThread main = sut.thread("main");

        assertThat(main.getStatus(), equalTo(ThreadStatus.SLEEPING));
        assertThat(reacquiring.getStatus(), equalTo(ThreadStatus.BLOCKED));

        assertThat(main.getAcquiredLocks().iterator().next(), equalTo(reacquiring.getWaitingToLock()));
        assertThat(reacquiring.getAcquiredLocks().size(), equalTo(2));
        assertThat(
                reacquiring.getStackTrace().getElement(0),
                equalTo(StackTrace.nativeElement("java.lang.Object", "wait"))
        );
    }

    private static final class Runner implements MethodRule {
        // This expects PidRuntimeFactory delegates to ThreadDumpFactory
        private static final PidRuntimeFactory prf = new PidRuntimeFactory();

        private Process process;
        private ProcessRuntime runtime = null;

        @Override
        public Statement apply(final Statement base, FrameworkMethod method, Object target) {
            try {
                process = run(Util.resourceFile(
                        ThreadDumpFactoryVendorTest.class, method.getName() + ".groovy"
                ));
            } catch (URISyntaxException ex) {
                throw new AssertionError(ex);
            } catch (Exception ex) {
                throw new AssertionError(ex);
            }

            return new Statement() {
                @Override
                public void evaluate() throws Throwable {
                    try {
                        base.evaluate();
                    } finally {
                        if (process != null) process.destroy();
                    }
                }
            };
        }

        private Process run(File resourceFile) throws IOException {
            ProcessBuilder pb = new ProcessBuilder(
                    System.getProperty("java.home") + "/bin/java",
                    "-cp", System.getProperty("surefire.real.class.path"), // Inherit from surefire process
                    "com.github.olivergondza.dumpling.cli.Main",
                    "groovy",
                    "--script", resourceFile.getAbsolutePath()
            );
            return pb.start();
        }

        public ProcessThread thread(@Nonnull String name) {
            return runtime().getThreads().where(nameIs(name)).onlyThread();
        }

        public ProcessRuntime runtime() {
            if (runtime != null) return runtime;

            try {
                int exit = process.exitValue();
                throw reportProblem(exit);
            } catch (IllegalThreadStateException ex) {
                // Still running as expected
                return runtime = waitForInitialized(process);
            }
        }

        private Error reportProblem(int exit) {
            StringBuilder out = new StringBuilder();
            StringBuilder err = new StringBuilder();
            try {
                byte[] buffer = new byte[1024];
                int len;
                while ((len = process.getErrorStream().read(buffer)) != -1) {
                    out.append(new String(buffer));
                }
                while ((len = process.getInputStream().read(buffer)) != -1) {
                    err.append(new String(buffer));
                }
            } catch (IOException ex) {
                throw new RuntimeException(ex);
            }

            return new AssertionError(
                    "Process under test terminated prematurelly. Exit code: "
                    + exit + "\nSTDOUT: " + out + "\nSTDERR: " + err
            );
        }

        private ProcessRuntime waitForInitialized(Process process) {
            int pid = getPid(process);
            ProcessRuntime runtime = prf.forProcess(pid);
            for (int i = 0; i < 10; i++) {
                pause(500);

                ProcessThread main = runtime.getThreads().where(nameIs("main")).onlyThread();

                for (StackTraceElement elem: main.getStackTrace().getElements()) {
                    if ("dumpling-script".equals(elem.getClassName()) && "run".equals(elem.getMethodName())) {
                        return prf.forProcess(pid);
                    }
                }

                runtime = prf.forProcess(pid);
            }

            throw new AssertionError("Process under test not initialized in time: " + runtime.getThreads());
        }

        private int getPid(Process process) {
            if (!"java.lang.UNIXProcess".equals(process.getClass().getCanonicalName())) {
                throw new AssertionError("Only unix processes are supported");
            }

            try {
                Field pidField = Class.forName("java.lang.UNIXProcess").getDeclaredField("pid");
                pidField.setAccessible(true);
                return (Integer) pidField.get(process);
            } catch (Exception e) {
                throw new AssertionError(e);
            }
        }
    };
}
