name: Dumpling CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17' ]
    name: Java ${{ matrix.Java }}
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - run: mvn --batch-mode --update-snapshots install
