name: Dumpling CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17', '21' ]
    name: Java ${{ matrix.Java }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - run: mvn --batch-mode --update-snapshots install
