name: Dumpling CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    name: Java ${{ matrix.Java }}
    steps:
    - uses: actions/checkout@v2
    - uses: AutoModality/action-xunit-viewer@v1.0.1
      id: xunit-viewer
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - run: mvn --batch-mode --update-snapshots install
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.xunit-viewer.outputs.report-name }}
        path: ${{ steps.xunit-viewer.outputs.report-dir }}
